### ISSUE TITLE
Build errors on macOS: ar: no archive members specified; error: no match for 'operator^' (operand types are 'Gs::Matrix4' {aka 'Gs::Matrix<float, 4, 4>'} and 'int')

### ISSUE THREAD

**Issue by barracuda156** [LukasBanana/GaussianLib#2]
First of all, making a static lib fails:
```
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/gausslib.dir/link.txt --verbose=ON
/opt/local/bin/ar qc build/libgausslib.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [build/libgausslib.a] Error 1
```
Then:
```
/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_GaussianLib/GaussianLib/work/GaussianLib-48dec59634058c7839009dfff4143a0384d2a997/test/test1.cpp: In function 'void affineMatrixTest1()':
/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_GaussianLib/GaussianLib/work/GaussianLib-48dec59634058c7839009dfff4143a0384d2a997/test/test1.cpp:168:48: error: no match for 'operator^' (operand types are 'Gs::Matrix4' {aka 'Gs::Matrix<float, 4, 4>'} and 'int')
  168 |     std::cout << "Inv(A) = " << std::endl << (A^-1) << std::endl;
      |                                               ~^~~
      |                                               | |
      |                                               | int
      |                                               Gs::Matrix4 {aka Gs::Matrix<float, 4, 4>}
/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_GaussianLib/GaussianLib/work/GaussianLib-48dec59634058c7839009dfff4143a0384d2a997/test/test1.cpp:169:52: error: no match for 'operator^' (operand types are 'Gs::Matrix4' {aka 'Gs::Matrix<float, 4, 4>'} and 'int')
  169 |     std::cout << "A*Inv(A) = " << std::endl << A*(A^-1) << std::endl;
      |                                                   ~^~~
      |                                                   | |
      |                                                   | int
      |                                                   Gs::Matrix4 {aka Gs::Matrix<float, 4, 4>}
/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_GaussianLib/GaussianLib/work/GaussianLib-48dec59634058c7839009dfff4143a0384d2a997/test/test1.cpp: In function 'void projectionTest1()':
/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_GaussianLib/GaussianLib/work/GaussianLib-48dec59634058c7839009dfff4143a0384d2a997/test/test1.cpp:302:26: error: 'class Gs::Vector<float, 4>' has no member named 'xy'; did you mean 'x'?
  302 |     std::cout << (R * a).xy() << std::endl;
      |                          ^~
      |                          x
make[2]: *** [CMakeFiles/test1.dir/test/test1.cpp.o] Error 1
```

**Comment by LukasBanana** [comment]
GaussianLib is a header only library, there's nothing to build for a static lib since there are no `.c`, `.cpp`, `.cxx`, `.m`, or `.mm` files.

As for the `A^-1` operation: The macro `GS_ENABLE_INVERSE_OPERATOR` has to be defined (i.e. `GaussLib_ENABLE_INVERSE_OPERATOR` option in CMake) which is disabled by default.
You can fix it by adding `#define GS_ENABLE_INVERSE_OPERATOR` before `<Gauss/Gauss.h>` is included or wrap those operations in `affineMatrixTest1()` in a `#ifdef GS_ENABLE_INVERSE_OPERATOR`/`#endif` block.

I'll update the test ~~by the end of today~~ as soon as I can.

**Comment by LukasBanana** [comment]
Fixed with [48ace64](https://github.com/LukasBanana/GaussianLib/commit/48ace64c272e12a8cbc2fb644c0520dce77dafc8)

**Comment by barracuda156** [comment]
> GaussianLib is a header only library, there's nothing to build for a static lib since there are no `.c`, `.cpp`, `.cxx`, `.m`, or `.mm` files.

@LukasBanana It needs the lib for tests, and for w/e reason it fails on Mac.
Apparently this part in CMakeLists:
```
# === Include directories ===

include_directories(${PROJECT_INCLUDE_DIR})


# === Binaries ===

add_library(gausslib STATIC ${FilesAll})
set_target_properties(gausslib PROPERTIES LINKER_LANGUAGE CXX DEBUG_POSTFIX "D")
target_compile_features(gausslib PRIVATE cxx_range_for)
```

I still get the same failure with creating a static lib:
```
--->  Configuring GaussianLib
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DGaussLib_REAL_DOUBLE=OFF -DGaussLib_ASSERT_EXCEPTION=OFF -DGaussLib_ENABLE_SWIZZLE_OPERATOR=OFF -DGaussLib_ENABLE_INVERSE_OPERATOR=OFF -DGaussLib_DISABLE_AUTO_INIT=OFF -DGaussLib_ROW_MAJOR_STORAGE=OFF -DGaussLib_ROW_VECTORS=OFF -DCMAKE_OSX_ARCHITECTURES="ppc" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.6" -DCMAKE_OSX_SYSROOT="/" /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/local/bin/gcc-mp-12 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/local/bin/g++-mp-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_OBJCXX_COMPILER
    CMAKE_OBJC_COMPILER
    CMAKE_POLICY_DEFAULT_CMP0025


-- Build files have been written to: /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968
--->  Building GaussianLib
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968" && /usr/bin/make -j8 -w all VERBOSE=ON 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
/opt/local/bin/cmake -S/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 -B/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 --check-build-system CMakeFiles/Makefile.cmake 0
/opt/local/bin/cmake -E cmake_progress_start /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/CMakeFiles /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968//CMakeFiles/progress.marks
/usr/bin/make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
/usr/bin/make  -f CMakeFiles/gausslib.dir/build.make CMakeFiles/gausslib.dir/depend
/usr/bin/make  -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/depend
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
cd /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 && /opt/local/bin/cmake -E cmake_depends "Unix Makefiles" /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/CMakeFiles/gausslib.dir/DependInfo.cmake --color=
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
cd /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 && /opt/local/bin/cmake -E cmake_depends "Unix Makefiles" /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968 /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/CMakeFiles/test1.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
/usr/bin/make  -f CMakeFiles/gausslib.dir/build.make CMakeFiles/gausslib.dir/build
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
/usr/bin/make  -f CMakeFiles/test1.dir/build.make CMakeFiles/test1.dir/build
make[2]: Entering directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
[ 25%] Linking CXX static library build/libgausslib.a
[ 50%] Building CXX object CMakeFiles/test1.dir/test/test1.cpp.o
[ 75%] Building CXX object CMakeFiles/test1.dir/test/test1_main.cpp.o
/opt/local/bin/cmake -P CMakeFiles/gausslib.dir/cmake_clean_target.cmake
/opt/local/bin/g++-mp-12  -I/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/include -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -MD -MT CMakeFiles/test1.dir/test/test1.cpp.o -MF CMakeFiles/test1.dir/test/test1.cpp.o.d -o CMakeFiles/test1.dir/test/test1.cpp.o -c /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/test/test1.cpp
/opt/local/bin/g++-mp-12  -I/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/include -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -MD -MT CMakeFiles/test1.dir/test/test1_main.cpp.o -MF CMakeFiles/test1.dir/test/test1_main.cpp.o.d -o CMakeFiles/test1.dir/test/test1_main.cpp.o -c /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-b88c7b0d632098f9f3956a42e239eaf63fc7d968/test/test1_main.cpp
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/gausslib.dir/link.txt --verbose=ON
/opt/local/bin/ar qc build/libgausslib.a 
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [build/libgausslib.a] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
make[1]: *** [CMakeFiles/gausslib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable build/test1
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/test1.dir/link.txt --verbose=ON
/opt/local/bin/g++-mp-12 -pipe -Os -DNDEBUG -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -arch ppc -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/local/lib -Wl,-headerpad_max_install_names CMakeFiles/test1.dir/test/test1.cpp.o CMakeFiles/test1.dir/test/test1_main.cpp.o -o build/test1  -Wl,-rpath,/opt/local/lib 
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
[100%] Built target test1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/LukasBanana-GaussianLib-b88c7b0'
make: *** [all] Error 2
```

**Comment by barracuda156** [comment]
I also think flags should be `-qc` and not `qc`, but fixing this does not solve the problem.

**Comment by LukasBanana** [comment]
I reproduced the issue and fixed it with [682b269](https://github.com/LukasBanana/GaussianLib/commit/682b269c602f231d44f9edca349baee5a4778c75). Thanks again for bringing this up. I also increased the required CMake version to 3.19 to make use of the `add_library(INTERFACE)` function.

**Comment by barracuda156** [comment]
Thank you, test exec build correctly now and runs:
```
--->  Testing GaussianLib
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-682b269c602f231d44f9edca349baee5a4778c75" && /opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_GaussianLib/GaussianLib/work/GaussianLib-682b269c602f231d44f9edca349baee5a4778c75/build/test1 
GaussianLib Test 1
==================
As = 
/ 1  0  0  10 \
| 0  0  1   5 |
| 0  1  0  -2 |
\ 0  0  0   1 /

C = 
/ 1  0  0  12 \
| 0  1  0  -4 |
\ 0  0  1   5 /

D = 
/ 4 \
| 2 |
| 0 |
\ 1 /

E = 
/ 16 \
| -2 |
\  5 /

a = ( 1 | 2 | 3 | 4 )
b = ( -4 | 0 | 2 | 1 )
a / || a || = ( 0.182574 | 0.365148 | 0.547723 | 0.730297 )
|| a - b || = 6.245
a ANGLE b = 1.32941
a.x = 1, a.y = 2, a.z = 3
a DOT b = 6
A = 
/ 1  -5  0  12.5 \
| 0   1  6  -7.8 |
| 0   0  0     0 |
\ 0   0  0     0 /

A^T = 
/    1     0  0  0 \
|   -5     1  0  0 |
|    0     6  0  0 |
\ 12.5  -7.8  0  0 /

B = 
/ 1  0  0  0 \
| 0  0  1  0 |
| 0  1  0  0 |
\ 0  0  0  1 /

A * B = 
/ 1  0  -5  12.5 \
| 0  6   1  -7.8 |
| 0  0   0     0 |
\ 0  0   0     0 /

A * a = ( 41 | -11.2 | 0 | 0 )
a * A = ( 1 | -3 | 12 | -3.1 )
C * b = ( 8 | -4 | 7 )
b * C^T = ( 8 | -4 | 7 )
Vector3(a) * C = ( 1 | 2 | 3 | 19 )
A = 
/ 1  0  -2   6 \
| 0  8   0  -4 |
| 0  1   2   0 |
\ 0  0   0   1 /

B = 
/ 1  0  -2   6 \
| 0  8   0  -4 |
| 0  1   2   0 |
\ 0  0   0   1 /

B^T = 
/  1   0  0  0 \
|  0   8  1  0 |
| -2   0  2  0 |
\  6  -4  0  1 /

Inv(B) = 
/ 1   -0.125    1   -6.5 \
| 0    0.125   -0    0.5 |
| 0  -0.0625  0.5  -0.25 |
\ 0        0    0      1 /

B*Inv(B) = 
/ 1  0  0  0 \
| 0  1  0  0 |
| 0  0  1  0 |
\ 0  0  0  1 /

| A | = 16
| B | = 16
Trace A = 12
Trace B = 12

A1 = 
/ 1  0  -2   6 \
| 0  8   0  -4 |
| 0  1   2   0 |
\ 0  0   0   1 /


A2 = 
/ -1.48803    1.39872  -0.910684   6 \
| -1.95214    2.66667    7.28547  -4 |
|  1.57735  -0.154701    1.57735   0 |
\        0          0          0   1 /


Lerp(A1, A2, 0.5) = 
/ -0.244017  0.699359  -1.45534   6 \
| -0.976068   5.33333   3.64273  -4 |
|  0.788675   0.42265   1.78868   0 |
\         0         0         0   1 /


5 * I3 = 
/ 5  0  0 \
| 0  5  0 |
\ 0  0  5 /

AffineMatrix3:
A = 
/ 1  0  -2 \
| 0  8   3 |
\ 0  0   1 /

A^-1 = 
/  1     -0       2 \
| -0  0.125  -0.375 |
\  0      0       1 /

A*A^-1 = 
/ 1  0  0 \
| 0  1  0 |
\ 0  0  1 /

AffineMatrix4:
B = 
/ 1   7  9  -6 \
| 2  -4  0   1 |
| 3   1  6  -2 |
\ 0   0  0   1 /

B^-1 = 
/  -1.33333  -1.83333   2   -2.16667 \
| -0.666667  -1.16667   1  -0.833333 |
|  0.777778   1.11111  -1    1.55556 |
\         0         0   0          1 /

B*B^-1 = 
/           1  4.76837e-07  0             0 \
|           0            1  0  -2.38419e-07 |
| 2.38419e-07  4.76837e-07  1             0 |
\           0            0  0             1 /

q0 = ( 0.707107 | 0 | 0 | 0.707107 )
q1 = ( 1 | 0 | -0 | -4.37114e-08 )
Slerp(0) = ( 0.707107 | 0 | 0 | 0.707107 )
Slerp(0.1) = ( 0.760406 | 0 | 0 | 0.649448 )
Slerp(0.2) = ( 0.809017 | 0 | 0 | 0.587785 )
Slerp(0.3) = ( 0.85264 | 0 | 0 | 0.522499 )
Slerp(0.4) = ( 0.891007 | 0 | 0 | 0.453991 )
Slerp(0.5) = ( 0.92388 | 0 | 0 | 0.382683 )
Slerp(0.6) = ( 0.951057 | 0 | 0 | 0.309017 )
Slerp(0.7) = ( 0.97237 | 0 | 0 | 0.233445 )
Slerp(0.8) = ( 0.987688 | 0 | 0 | 0.156434 )
Slerp(0.9) = ( 0.996917 | 0 | 0 | 0.0784591 )
Slerp(1) = ( 1 | 0 | 0 | -4.37114e-08 )
m = 
/  1             1  1 \
| -1  -4.37114e-08  1 |
\  1            -1  1 /

Quaterion(m) = ( -0.485071 | 0 | -0.485071 | 0.727607 )
q0       = ( 0.653282 | 0.270598 | -0.270598 | 0.653282 )
q1       = ( 1 | 0 | -0 | -4.37114e-08 )
q0 * q0  = ( 0.853553 | 0.353553 | -0.353553 | -0.146447 )
Dot(q0, q0)  = 1
q0 *= q0 = ( 0.853553 | 0.353553 | -0.353553 | -0.146447 )
A = 
/ 1  0  0         4 \
| 0  1  0         2 |
| 0  0  1  -1.66667 |
\ 0  0  0         1 /

B = 
/ 1  0  0   4 \
| 0  2  0   4 |
| 0  0  3  -5 |
\ 0  0  0   1 /

A^-1 = 
/ 1  0  0       -4 \
| 0  1  0       -2 |
| 0  0  1  1.66667 |
\ 0  0  0        1 /

A*A^-1 = 
/ 1  0  0  0 \
| 0  1  0  0 |
| 0  0  1  0 |
\ 0  0  0  1 /

a = ( 4 | 2 | -1.66667 | 1 )
b = ( 4 | 4 | -5 | 1 )
Perspective Projection P = 
/ 0.995284        0       0        0 \
|        0  1.32704       0        0 |
|        0        0  1.0101  -1.0101 |
\        0        0       1        0 /

Orthogonal  Projection Q = 
/ 0.0025           0         0          0 \
|      0  0.00333333         0          0 |
|      0           0  0.010101  -0.010101 |
\      0           0         0          1 /

Planar      Projection R = 
/ 0.0025            0  0  -1 \
|      0  -0.00333333  0   1 |
|      0            0  1   0 |
\      0            0  0   1 /

P*P^-1 = 
/ 1  0  0  0 \
| 0  1  0  0 |
| 0  0  1  0 |
\ 0  0  0  1 /

a = ( 50 | 0 | 0 | 1 )
a = ( 1 | 2 | 3 )
b = ( 4 | 5 | 6 )
c = ( 1 | 2 | 3 )
a equals b ? No
a equals c ? Yes
x = 1
y = 2
z = 1
x equals y ? No
x equals z ? Yes
x = ( 12 | 5 | 3 | -9 | 16 | -4 | 0 | 0 | 0 | 0 )
A = 
/ 1  4  0   0  0  0  0   0   0  0 \
| 0  1  0   0  0  0  0   0   0  0 |
| 0  0  1   0  0  0  0  -5   0  0 |
| 0  0  0   1  0  0  0   0   0  0 |
| 0  0  0   0  6  0  0   0   0  0 |
| 0  0  0  18  0  1  0   0   0  0 |
| 0  0  0   0  0  0  1   0   0  0 |
| 0  0  0   0  0  0  0   1   0  0 |
| 0  0  0   0  0  0  0   0  -2  0 |
\ 0  0  0   0  0  0  0   0   0  1 /

A*x = ( 32 | 5 | 3 | -9 | 96 | -166 | 0 | 0 | 0 | 0 )
Trace(A) = 12
epsilon<float> = 1e-06
epsilon<double> = 1e-08
0.1 >= 1e-06
pi = 3.14159
cartesian coordinate a = ( 1 | 2 | 3 )
spherical coordinate b = ( radius: 3.74166, theta: 0.640522, phi: 1.10715 )
cartesian coordinate b = ( 1 | 2 | 3 )

cartesian coordinate a = ( -4 | 0 | 8 )
spherical coordinate b = ( radius: 8.94427, theta: 0.463648, phi: 3.14159 )
cartesian coordinate b = ( -4 | 6.03983e-07 | 8 )

cartesian coordinate a = ( 0 | 0 | 0 )
spherical coordinate b = ( radius: 0, theta: 0, phi: 0 )
cartesian coordinate b = ( 0 | 0 | 0 )

cartesian coordinate a = ( 0.01 | -0.08 | 0.0005 )
spherical coordinate b = ( radius: 0.0806241, theta: 1.56459, phi: -1.44644 )
cartesian coordinate b = ( 0.01 | -0.08 | 0.000500003 )

cartesian coordinate a = ( -3948 | 4933 | -239382 )
spherical coordinate b = ( radius: 239465, theta: 3.1152, phi: 2.24573 )
cartesian coordinate b = ( -3948.02 | 4933.03 | -239382 )

a = ( 1 | 0 | 0 )
b = ( 0 | 1 | 0 )
Cross(a, b) = ( 0 | 0 | 1 )
vec = ( 1 | 2 | 3 ), axis = ( 0 | 1 | 0 ), angle = 0.785398, x = ( 2.82843 | 2 | 1.41421 )
a = ( 1 | 2 | 3 ), b = ( 2 | 3 | 4 ), a < b: true
A = 
/ 1  0  0 \
| 0  1  0 |
\ 0  5  1 /
B = 
/ 1  0  0 \
| 0  1  0 |
\ 0  0  1 /
A < B: false
A = 
/  1   2   3   4 \
| -5  -6  -7  -8 |
|  9  10  11  12 |
\ 13  14  15  16 /

B = 
/  1   2   3   4 \
| -5  -6  -7  -8 |
|  9  10  11  12 |
\  0   0   0   1 /

A = 
/ 1         0          0    7 \
| 0  0.707107  -0.707107    3 |
| 0  0.707107   0.707107  -12 |
\ 0         0          0    1 /

Rcp(3.14159) = 0.31831
Rcp(( 1 | 2 | 3 )) = ( 1 | 0.5 | 0.333333 )
Rcp(
/ 1  0  0  0 \
| 0  1  0  0 |
| 0  0  1  0 |
\ 0  0  0  1 /
) = 
/   1  inf  inf  inf \
| inf    1  inf  inf |
| inf  inf    1  inf |
\ inf  inf  inf    1 /

sin(( 0.5 | 1 | 1.5 )) = ( 0.479426 | 0.841471 | 0.997495 )
acos(( 0.5 | 1 | 1.5 )) = ( 1.0472 | 0 | nan )
floor(( 0.5 | 1 | 1.5 )) = ( 0 | 1 | 1 )
ceil(( 0.5 | 1 | 1.5 )) = ( 1 | 1 | 2 )
sin(
/ 1  2 \
\ 3  4 /
) = 
/ 0.841471   0.909297 \
\  0.14112  -0.756802 /

v                               = ( 2.5 | 3.4 | 9.5 )
1 / v                           = ( 0.4 | 0.294118 | 0.105263 )
v / v.x                         = ( 1 | 1.36 | 3.8 )
v /= v.x                        = ( 1 | 1.36 | 3.8 )
Vector2(v)                      = ( 1 | 1.36 )
Vector4(Vector2(v), Vector2(v)) = ( 1 | 1.36 | 1 | 1.36 )
v0          = ( 0 | 0 | 0 | 1 )
v1          = ( 3 | -0.5 | 0 | 1 )
v2          = ( 0.5 | 1 | 2.5 | 1 )
v1 + v2     = ( 3.5 | 0.5 | 2.5 | 2 )
v1 * v2     = ( 1.5 | -0.5 | 0 | 1 )
v1 * -5     = ( -15 | 2.5 | -0 | -5 )
Dot(v1, v2) = 2
|v1|        = 3.20156
v1 / |v1|   = ( 0.937043 | -0.156174 | 0 | 0.312348 )
v0          = ( 0 | 0 | 0 | 1 )
v1          = ( 3 | -0.5 | 0 | 1 )
v2          = ( 0.5 | 1 | 2.5 | 1 )
v1 + v2     = ( 3.5 | 0.5 | 2.5 | 2 )
v1 * v2     = ( 1.5 | -0.5 | 0 | 1 )
v1 * -5     = ( -15 | 2.5 | -0 | -5 )
Dot(v1, v2) = 2
|v1|        = 3.20156
v1 / |v1|   = ( 0.937043 | -0.156174 | 0 | 0.312348 )
A = 
/ 0  1  0 \
| 2  0  0 |
\ 0  0  3 /

```
